=pod

=head1 NAME

    idea_site_startup.pod

=head1 VERSION

    v.0.0.1

=head1 DESCRIPTION

=head2 Visual

Boutique impression: bottle of wines, artworks, feeling of classical music....
B<and code>!

All fitted together in the same machine:)

=head2 Text

The bottle of wines are not placed here just because we love to drink wine.
They depict our mission: not to provide you just another frameworked web site,
but make for you a unique site, personally developed for your.
And of course, developed with the same joy as with we drink wine.

=head1 TODO

=head1 AUTHOR

    Iva E.Popova (iva.e.popova@gmail.com)

=head1 COPYRIGHT AND LICENSE

    2014, Artistic License 2.0

=cut
