


=pod

=head1 Title

Думите подплътяват мисълтта. Обрамчват я със структура.

=head2 Content
Живеем във времена, в които програмистите са по-добре платени от музикантите, писателите, художниците. Да видим, дали ще станат и по-уважавани. [да се продължи в контекста на дали добрата заплата е определящ фактор за да бъде
една професия уважавана].

Силните стават слаби, слабите силни [анализ: по времето на соца силните на деня бяха народните артисти, музиканти, писатели...]



Думите подплътяват мисълтта. Обрамчват я със структура.
Ако напиша нещо 100 пъти, дали ще престана да го правя ? Вероятно на 99 път волята ми ще се е уморила, и аз просто (подсъзнателно) ще възприема написаното.

=cut


